package com.example.trustR.model;

public enum SignalType {
    FAILED_ACTION_ATTEMPT,
    FAILED_ACTION_ATTEMPTS_5_MIN,
    FAILED_ACTION_ATTEMPTS_1_HOUR,
    SUCCESSFUL_ACTION,
    SUCCESS_RATE_5_MIN,
    RATE_LIMIT_HIT,
    RATE_LIMIT_HITS_10_MIN,
    POLICY_VIOLATION_REPORTED,
    POLICY_VIOLATIONS_24_HOURS
}
